services:
  server:
    image: ghcr.io/yash2k26/predictpro/backend:latest
    ports:
      - "1001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=https://predictpro.yashb.xyz
    restart: unless-stopped

  web:
    image: ghcr.io/yash2k26/predictpro/web:latest
    ports:
      - "1000:3000"
    restart: unless-stopped
